In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/kaiyungtan/challenge-data-analysis/master/data/clean/belgium_real_estate.csv',index_col=0)
df.head()

,postal_code,city_name,type_of_property,price,number_of_rooms,house_area,fully_equipped_kitchen,open_fire,terrace,garden,surface_of_the_land,number_of_facades,swimming_pool,state_of_the_building,lattitude,longitude,province,region
0,1050,Ixelles,0,340000,6,203,1,0,1,0,95,2,0,to be done up,4.381571,50.822285,Bruxelles-Capitale,Bruxelles
1,1050,Ixelles,0,520000,4,200,0,0,0,0,69,2,0,to renovate,4.381571,50.822285,Bruxelles-Capitale,Bruxelles
2,1050,Ixelles,0,599000,4,160,1,0,1,1,100,2,0,to be done up,4.381571,50.822285,Bruxelles-Capitale,Bruxelles
3,1050,Ixelles,0,599000,3,160,1,0,1,1,130,2,0,good,4.381571,50.822285,Bruxelles-Capitale,Bruxelles
4,1050,Ixelles,0,575000,3,171,0,0,0,0,46,2,0,just renovated,4.381571,50.822285,Bruxelles-Capitale,Bruxelles

In [ ]:
df.shape

(40395, 18)